name: linting

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "*.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Installing dependencies
        run: npm install

      - name: Linting
        run: npm run lint
